module.exports = {
  extends: ['stylelint-config-recommended-vue'],
  plugins: ['stylelint-order'],
  ignoreFiles: ['**/node_modules/**', '**/.nuxt/**', '**/dist/**'],
  customSyntax: 'postcss-scss',
  overrides: [
    {
      files: ['**/*.vue'],
      customSyntax: 'postcss-html',
    },
  ],
  rules: {
    'at-rule-no-unknown': null,
    'function-no-unknown': null,
    'property-no-unknown': [
      true,
      {
        ignoreProperties: ['overflow-scrolling'],
      },
    ],
    'at-rule-disallowed-list': ['extend'],
    'at-rule-empty-line-before': 'never',
    'no-descending-specificity': null,
    'no-empty-source': null,
    'order/properties-order': [
      'content',
      'position',
      'top',
      'right',
      'bottom',
      'left',
      'box-sizing',
      'z-index',
      'float',
      'clear',
      'overflow',
      'overflow-x',
      'overflow-y',
      'table-layout',
      'border-collapse',
      'border-spacing',
      'empty-cells',
      'caption-side',
      'columns',
      'column-count',
      'column-gap',
      'column-fill',
      'column-rule',
      'column-span',
      'column-width',
      'grid-gap',
      'grid-template-columns',
      'flex',
      'flex-grow',
      'flex-shrink',
      'flex-basis',
      'flex-flow',
      'flex-direction',
      'flex-wrap',
      'justify-content',
      'align-content',
      'align-items',
      'align-self',
      'order',
      'display',
      'width',
      'min-width',
      'max-width',
      'height',
      'min-height',
      'max-height',
      'margin',
      'margin-top',
      'margin-right',
      'margin-bottom',
      'margin-left',
      'padding',
      'padding-top',
      'padding-right',
      'padding-bottom',
      'padding-left',
      'font',
      'font-family',
      'font-size',
      'font-smoothing',
      'font-style',
      'font-variant',
      'font-weight',
      'color',
      'line-height',
      'letter-spacing',
      'text-align',
      'vertical-align',
      'text-decoration',
      'text-decoration-color',
      'text-decoration-style',
      'text-decoration-line',
      'text-indent',
      'text-overflow',
      'text-rendering',
      'text-shadow',
      'text-transform',
      'text-wrap',
      'white-space',
      'word-break',
      'word-spacing',
      'word-wrap',
      'text-shadow',
      'border',
      'border-top',
      'border-right',
      'border-bottom',
      'border-left',
      'border-width',
      'border-top-width',
      'border-right-width',
      'border-bottom-width',
      'border-left-width',
      'border-style',
      'border-top-style',
      'border-right-style',
      'border-bottom-style',
      'border-left-style',
      'border-radius',
      'border-top-left-radius',
      'border-top-right-radius',
      'border-bottom-left-radius',
      'border-bottom-right-radius',
      'border-color',
      'border-top-color',
      'border-right-color',
      'border-bottom-color',
      'border-left-color',
      'border-image',
      'border-top-image',
      'border-right-image',
      'border-bottom-image',
      'border-left-image',
      'box-shadow',
      'background',
      'background-attachment',
      'background-clip',
      'background-color',
      'background-image',
      'background-repeat',
      'background-position',
      'background-size',
      'background-origin',
      'list-style',
      'list-style-type',
      'list-style-position',
      'list-style-image',
      'translate',
      'rotate',
      'scale',
      'transform',
      'transform-box',
      'transform-origin',
      'transform-style',
      'cursor',
      'pointer-events',
      'user-select',
      'appearance',
      'animation',
      'animation-name',
      'animation-timing-function',
      'transition',
      'transition-delay',
      'transition-duration',
      'transition-property',
      'transition-timing-function',
      'will-change',
      'visibility',
      'opacity',
      'fill',
      'quotes',
      'conter-increment',
      'conter-reset',
      'outline',
      'outline-color',
      'outline-offset',
      'outline-style',
      'outline-width',
      'resize',
      'speak',
    ],
  },
}
